package mongo

import (
	"context"

	"web-app-firewall-ml-detection/internal/core"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

type LogRepository struct {
	db *mongo.Database
}

func NewLogRepository(client *mongo.Client) *LogRepository {
	return &LogRepository{
		db: client.Database("waf"),
	}
}

func (r *LogRepository) LogAttack(ctx context.Context, logEntry core.AttackLog) error {
	// If ID is auto-generated by mongo, we can omit it or generate it here.
	// We'll let Mongo generate it if empty, but structs usually need the field.
	_, err := r.db.Collection("logs").InsertOne(ctx, logEntry)
	return err
}

func (r *LogRepository) GetLogs(ctx context.Context, filter core.LogFilter) (*core.PaginatedLogs, error) {
	mongoFilter := bson.M{}
	
	// Basic Validation
	if filter.DomainID != "" {
		mongoFilter["domain_id"] = filter.DomainID
		// Note: ownership check should happen in Service layer, not Repo layer
	} else {
		mongoFilter["user_id"] = filter.UserID
	}

	totalItems, err := r.db.Collection("logs").CountDocuments(ctx, mongoFilter)
	if err != nil { return nil, err }

	if filter.Page < 1 { filter.Page = 1 }
	if filter.Limit < 1 { filter.Limit = 20 }
	skip := (filter.Page - 1) * filter.Limit

	totalPages := int64(0)
	if filter.Limit > 0 {
		totalPages = (totalItems + filter.Limit - 1) / filter.Limit
	}

	opts := options.Find().
		SetSort(bson.D{{Key: "timestamp", Value: -1}}).
		SetSkip(skip).
		SetLimit(filter.Limit)

	cursor, err := r.db.Collection("logs").Find(ctx, mongoFilter, opts)
	if err != nil { return nil, err }
	defer cursor.Close(ctx)

	var logs []core.AttackLog
	if err = cursor.All(ctx, &logs); err != nil { return nil, err }
	if logs == nil { logs = []core.AttackLog{} }

	return &core.PaginatedLogs{
		Data: logs,
		Pagination: struct {
			CurrentPage int64 `json:"current_page"`
			TotalPages  int64 `json:"total_pages"`
			TotalItems  int64 `json:"total_items"`
			PerPage     int64 `json:"per_page"`
		}{
			CurrentPage: filter.Page,
			TotalPages:  totalPages,
			TotalItems:  totalItems,
			PerPage:     filter.Limit,
		},
	}, nil
}